<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Backend.Domain\UCR.EB.BioMicroscopeAdmin.Backend.Domain.csproj" />
    <ProjectReference Include="..\Backend.Application\UCR.EB.BioMicroscopeAdmin.Backend.Application.csproj" />
    <ProjectReference Include="..\Backend.Infrastructure\UCR.EB.BioMicroscopeAdmin.Backend.Infrastructure.csproj" />
    <ProjectReference Include="..\Backend.Presentation\UCR.EB.BioMicroscopeAdmin.Backend.Presentation.csproj" />
  </ItemGroup>

</Project>
