// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UCR.EB.BioMicroscopeAdmin.Backend.Infrastructure.Persistence;

#nullable disable

namespace UCR.EB.BioMicroscopeAdmin.Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UCR.EB.BioMicroscopeAdmin.Backend.Domain.Entities.Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("caja", (string)null);
                });

            modelBuilder.Entity("UCR.EB.BioMicroscopeAdmin.Backend.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("grupo", (string)null);
                });

            modelBuilder.Entity("UCR.EB.BioMicroscopeAdmin.Backend.Domain.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_archivo");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("SlideId")
                        .HasColumnType("integer")
                        .HasColumnName("lamina_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_carga");

                    b.HasKey("Id");

                    b.HasIndex("SlideId");

                    b.ToTable("imagen", null, t =>
                        {
                            t.HasCheckConstraint("CK_imagen_orden", "orden >= 1 AND orden <= 6");
                        });
                });

            modelBuilder.Entity("UCR.EB.BioMicroscopeAdmin.Backend.Domain.Entities.Slide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoxId")
                        .HasColumnType("integer")
                        .HasColumnName("caja_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.ToTable("lamina", (string)null);
                });

            modelBuilder.Entity("UCR.EB.BioMicroscopeAdmin.Backend.Domain.Entities.Box", b =>
                {
                    b.HasOne("UCR.EB.BioMicroscopeAdmin.Backend.Domain.Entities.Group", "Group")
                        .WithMany("Boxes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UCR.EB.BioMicroscopeAdmin.Backend.Domain.Entities.Image", b =>
                {
                    b.HasOne("UCR.EB.BioMicroscopeAdmin.Backend.Domain.Entities.Slide", "Slide")
                        .WithMany("Images")
                        .HasForeignKey("SlideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slide");
                });

            modelBuilder.Entity("UCR.EB.BioMicroscopeAdmin.Backend.Domain.Entities.Slide", b =>
                {
                    b.HasOne("UCR.EB.BioMicroscopeAdmin.Backend.Domain.Entities.Box", "Box")
                        .WithMany("Slides")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");
                });

            modelBuilder.Entity("UCR.EB.BioMicroscopeAdmin.Backend.Domain.Entities.Box", b =>
                {
                    b.Navigation("Slides");
                });

            modelBuilder.Entity("UCR.EB.BioMicroscopeAdmin.Backend.Domain.Entities.Group", b =>
                {
                    b.Navigation("Boxes");
                });

            modelBuilder.Entity("UCR.EB.BioMicroscopeAdmin.Backend.Domain.Entities.Slide", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
